name: power_geojson_example
description: Demonstrates how to use the power_geojson plugin.

publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  power_geojson:
    path: ../

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  flutter_map: ^5.0.0
  # flutter_map_marker_cluster: ^1.1.1
  latlong2: ^0.9.0
  console_tools: ^1.0.0
  proj4dart: ^2.1.0
  tuple: ^2.0.1
  get: ^4.6.5
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/geojsons/
