name: power_geojson
description: A Powerful tool for Geojson with flutter_map, can be styled from its properties, and use buffers, also supports esri json, and soon supports multiple projection and coordinate systems
version: 0.0.1
homepage: htpps://github.com/ymrabti/power_geojson

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  console_tools: ^1.0.0
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  geodesy: ^0.7.0
  geojson_vi: ^2.2.0
  http: ^1.0.0
  latlong2: ^0.9.0
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.0.2
  point_in_polygon: ^1.0.0
  turf: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/icons/
  plugin:
    platforms:
      android:
        package: com.ymrabtipacks.power_geojson
        pluginClass: PowerGeojsonPlugin
      ios:
        pluginClass: PowerGeojsonPlugin
