name: power_geojson
description: A Powerful tool for Geojson with flutter_map, styled from properties, supports esri json, soon supports multiple projection and coordinate systems
version: "1.2.3-pre.1+6"
homepage: https://github.com/ymrabti/power_geojson

environment:
    sdk: ^3.5.4
    flutter: ">=2.18.0"

dependencies:
    flutter:
        sdk: flutter
    collection: ^1.18.0
    console_tools: ^1.0.1
    enhanced_future_builder: ^2.0.0
    flutter_map: ^7.0.2
    geodesy: ^0.10.2
    geojson_vi: ^2.2.5
    http: ^1.2.2
    latlong2: ^0.9.1
    # flutter_map_marker_cluster: ^1.4.0
    animated_stack_widget: ^0.0.4
    provider: ^6.1.2
    # To do: Add StreamBuilder

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    assets:
        - packages/power_geojson/icons/drop-pin.png
