name: Publish to pub.dev

on:
  push:
    branches:
      - develop
    tags:
      - "v*"

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
